#!/usr/bin/env python3
"""
Generates the star field for the website (Hugo partial + background images).

History, for future me:
  v1 (stars.js, RIP): ~1000 box-shadow "stars" (squares!) animated by a
     requestAnimationFrame loop. Laggy, and box-shadows are square.
  v2 (pattern SVG + SMIL): round stars, zero JS, but Firefox runs SMIL
     on the main thread AND re-rasterizes pattern content every frame
     when opacity animates inside it — slower than v1 there. SMIL's clock
     also pauses on hidden tabs, so stars jumped when switching tabs.
  v3 (this): each star layer is a plain <div> with a tiny static SVG as
     a repeating background. Drift = CSS transform animation, twinkle =
     CSS opacity animation. Both run on the compositor in every browser
     (Firefox included) and follow wall-clock time, so they stay in sync
     across tab switches like the old Date.now() approach. The seamless
     loop is free: translating by exactly one tile-height repeats the
     background perfectly.

Twinkles: stars fade in groups — each group is its own div sharing one
CSS animation (random membership + random phase/duration keeps it organic).

Output:
  layouts/partials/stars.html     (the divs + a <style> block)
  static/img/stars/l{layer}g{group}-{theme}.svg

Regenerate with: python3 generate_stars.py
"""

import os

BASE = os.path.dirname(os.path.abspath(__file__))
STATIC = os.path.join(BASE, "static", "img", "stars")
PARTIAL = os.path.join(BASE, "layouts", "partials", "stars.html")

TW, TH = 480, 600        # background tile (px)
SEED = 42069             # same seed as the old stars.js, lol

# (base radius, star count per tile, drift duration in seconds)
# Counts keep the old site's 7:2:1 layer ratio (700/200/100).
LAYERS = [
    (0.7, 78, 50),
    (1.2, 22, 100),
    (1.8, 11, 150),
]

TWINKLE_GROUPS = 4  # fade groups per layer; more = more organic, more divs

# Same colors the old --star-color CSS var held, baked into the SVGs.
THEMES = {
    "light": "#0000007a",
    "dark": "#ffffff7a",
}


# LCG stands for "Linear Congruential Generator". ✨ The more you know ✨
def lcg(seed):
    state = seed
    while True:
        state = (1103515245 * state + 12345) % 2147483648
        yield state / 2147483648


def make():
    gen = lcg(SEED)
    rnd = lambda: next(gen)

    # First pass: assign stars to twinkle groups (same random stream for
    # every theme, so light and dark tiles match exactly).
    layer_groups = []
    for base_r, count, drift in LAYERS:
        groups = [[] for _ in range(TWINKLE_GROUPS)]
        for _ in range(count):
            groups[int(rnd() * TWINKLE_GROUPS)].append(
                f'<circle cx="{rnd() * TW:.0f}" cy="{rnd() * TH:.0f}" '
                f'r="{base_r * (0.75 + rnd() * 0.5):.1f}"/>'
            )
        rendered = []
        for stars in groups:
            if not stars:
                continue
            dur = 3 + rnd() * 5        # twinkle cycle
            delay = -rnd() * dur       # negative delay = phase offset
            o_min = 0.08 + rnd() * 0.17
            rendered.append(("".join(stars), dur, delay, o_min))
        layer_groups.append((drift, rendered))

    os.makedirs(STATIC, exist_ok=True)

    rules_light, rules_dark, divs = [], [], []
    for li, (drift, groups) in enumerate(layer_groups):
        for gi, (stars, dur, delay, o_min) in enumerate(groups):
            key = f"l{li}g{gi}"
            for theme, fill in THEMES.items():
                with open(os.path.join(STATIC, f"{key}-{theme}.svg"), "w") as f:
                    f.write(
                        f'<svg xmlns="http://www.w3.org/2000/svg" width="{TW}" height="{TH}" '
                        f'viewBox="0 0 {TW} {TH}" fill="{fill}">' + stars + '</svg>\n'
                    )
            rules_light.append(f'.sk-{key}{{background-image:url(/img/stars/{key}-light.svg)}}')
            rules_dark.append(f'.sk-{key}{{background-image:url(/img/stars/{key}-dark.svg)}}')
            # Two animations on one element: sk-drift moves the div up by
            # exactly one tile (seamless loop), sk-tk fades it in/out.
            divs.append(
                f'<div class="sk sk-{key}" style="animation:sk-drift {drift}s linear infinite,'
                f'sk-tk {dur:.1f}s ease-in-out {delay:.1f}s infinite;--sk-min:{o_min:.2f}"></div>'
            )

    # Each div is oversized (top -200%, height 500%) so it still covers
    # the viewport at the far end of its -TH travel, on any screen size.
    style = (
        "/* Generated by generate_stars.py — do not edit by hand */\n"
        "#star-container .sk{position:absolute;left:0;top:-200%;width:100%;height:500%;"
        f"background-repeat:repeat;background-size:{TW}px {TH}px;will-change:transform,opacity;}}\n"
        f"@keyframes sk-drift{{to{{transform:translateY(-{TH}px)}}}}\n"
        "@keyframes sk-tk{0%,100%{opacity:var(--sk-min,.15)}50%{opacity:1}}\n"
        + "\n".join(rules_light) + "\n"
        + "@media (prefers-color-scheme: dark){\n" + "\n".join(rules_dark) + "\n}\n"
    )

    n_svgs = sum(len(g) for _, g in layer_groups) * len(THEMES)
    return (
        '<div id="star-container" class="DO_NOT_OPEN_VERY_LAGGY" aria-hidden="true">\n'
        '<style>\n' + style + '</style>\n' + "\n".join(divs) + '\n</div>\n'
    ), n_svgs


if __name__ == "__main__":
    partial, n_svgs = make()
    with open(PARTIAL, "w") as f:
        f.write(partial)
    n_divs = partial.count('<div class="sk')
    print(f"wrote {PARTIAL} ({os.path.getsize(PARTIAL)} bytes, {n_divs} star divs)")
    print(f"wrote {n_svgs} tile SVGs to {STATIC}")
